### ISSUE TITLE
Wrong path to image assets?

### ISSUE THREAD

**Issue by Invulner** [newtriks/generator-react-webpack#199]
If run 'npm dist' after install (without any modifications) and open 'dist/index.html' in the browser then you'll see that there's no image - http://joxi.ru/82Q4jwes1KXldm . Looks like first '/' isn't necessary. Not a big deal, just looks like a small bug.
Anyway, great work! This generator open new possibilities for me to learn new tools in convenient way.

**Comment by weblogixx** [comment]
Hi @Invulner,

thanks for the hint. This will get fixed in the next version of the generator.

**Comment by bentaly** [comment]
Any update or a work around for this issue? I havent been able to solve it yet (if i do ill post here)

**Comment by bentaly** [comment]
I changed the module.exports in defaults.js to:

`module.exports = {
  srcPath: srcPath,
  publicPath: 'assets/',
  port: dfltPort,
  getDefaultModules: getDefaultModules,
  postcss: function () {
    return [];
  }
};`

Note the lack of a slash on the front of the 'assets/'  path name

**Comment by weblogixx** [comment]
Hi @Invulner,

I will provide a release tomorrow, that will have this bug fixed. After this one, all created paths will be relative, making the generated sources easier to maintain.

@bentaly:
Thanks for your feedback. There was one little minor addition that was missing from your example, just changing the publicPath will result in not found errors because of the devServer config. Running it on your own servers will work, though.

**Comment by lpillmann** [comment]
Hi @weblogixx,

Just so you know, I came across this bug even after the release (I've set up the project folder this week). Maybe something still missing?

I fixed the problem as @bentaly suggested.
